### ISSUE TITLE
Unique Id is not generating

### ISSUE THREAD

**Issue by tushargoel86** [LableOrg/java-uniqueid#2]
Hii,

I tried to use this API to generate unique id over ZooKeeper single and cluster instance. But it is not generating. it always returns 0.. Not sure its API issue or my bug.. Please help.. 

Here is code..

                 final String zookeeperQuorum = "localhost";
		ZooKeeperConnection conn = new ZooKeeperConnection(zookeeperQuorum);
		final String znode = "/unique-id-generator";
		IDGenerator generator = SynchronizedUniqueIDGeneratorFactory.generatorFor(conn, znode, Mode.SPREAD);
		byte []data = generator.generate();
		System.out.println(IDBuilder.parse(data));
		generator.close();

result:

{
  mode: SPREAD,
  timestamp: 1554008641654,
  sequence: 0,
  generator: 0,
  cluster: 1
}

**Comment by jdhoek** [comment]
Hello,

That looks like a valid value. If you call `generator.generate();` a number of times in a loop you'll see the `sequence` field increase until the next timestamp value ticks over.

If you use this library from two threads or two computers at the same time with the same ZooKeeper quorum and the same nodes, you will see that one of those generator claims `generator: 0` and the other `generator: 1`.

The meaning of the fields `IDBuilder.parse` returns is documented here:

https://github.com/LableOrg/java-uniqueid/blob/master/doc/eight-byte-id-structure.md

The whole 8 byte value is the unique identifier. Normally you wouldn't parse the value returned except for debugging (although it can tell you when it was generated).

If you want to verify that the identifiers returned are unique as a test, you could set up something like this test:

https://github.com/LableOrg/java-uniqueid/blob/master/uniqueid-zookeeper/src/test/java/org/lable/oss/uniqueid/zookeeper/SynchronizedUniqueIDGeneratorIT.java#L87
